-- SKY-220: drop the summary_md / summary_stale columns from projects.
--
-- The original SKY-220 design (v1) leaned on a derived per-project
-- summary that the classifier read instead of the raw KB. The shipping
-- design (v2) is a per-project quorum vote where each Haiku call reads
-- its project's name + description + KB inline, so the summary
-- intermediate is no longer needed.
--
-- SQLite supports ALTER TABLE DROP COLUMN since 3.35 (modernc.org/sqlite
-- ships a recent enough engine). Neither column is indexed or
-- referenced by FKs, so the drop has no constraint cleanup to do.
--
-- Forward-only and idempotent: running against a DB that already
-- dropped these columns is a no-op because the migration runner skips
-- versions present in schema_migrations. Running against a DB that
-- never had them (impossible in practice — every prior install came
-- through 20260502_001_projects.sql which adds them) would fail at the
-- ALTER step; we accept that because the columns are guaranteed by
-- the baseline path.
ALTER TABLE projects DROP COLUMN summary_md;
ALTER TABLE projects DROP COLUMN summary_stale;
