// Package agentmeta builds the disclosure / metadata footer appended
// to agent-published content (review bodies, PR bodies, future surfaces
// like issue comments). Consolidates what used to live as two near-
// duplicate builders in cmd/exec/gh/pr.go and internal/server/
// reviews_handler.go — both did the same job (compute elapsed + cost,
// pretty-print model name, render markdown footer) but disagreed on
// the cost source.
//
// The cost source is now uniform: read runs.total_cost_usd if it's
// populated (the standard path; CompleteAgentRun fills it in at run
// terminal). Fall back to recomputing from RunTokenTotals only when
// the column is nil — that branch covers the still-running standalone
// CLI mode where the run hasn't completed yet. With the queue-then-
// approve flow, both review submit and PR submit run AFTER the
// agent has terminated, so the column is always populated and the
// fallback is rare.
package agentmeta

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/sky-ai-eng/triage-factory/internal/ai"
	"github.com/sky-ai-eng/triage-factory/internal/db"
	"github.com/sky-ai-eng/triage-factory/internal/domain"
	"github.com/sky-ai-eng/triage-factory/internal/runmode"
)

// Build returns the markdown footer to append to an agent-authored
// body. kind is the noun in the disclaimer ("review", "PR", future
// surfaces). Always begins with "\n\n---\n" so the caller just
// concatenates: `body + agentmeta.Build(...)`.
//
// Empty runID returns an empty string — there's nothing to disclose
// when no agent run is associated with the content. Callers safely
// concatenate the result; a human running the CLI directly (no
// delegation context) gets their body back unmodified instead of a
// "This was partially generated by AI" lie.
//
// On DB lookup failure with a non-empty runID we fall back to the
// bare branding-only footer rather than blocking the submit — the
// disclosure is still meaningful (a run did exist) even if we
// couldn't render the metrics.
func Build(agentRuns db.AgentRunStore, runID, kind string) string {
	if runID == "" {
		return ""
	}

	disclaimer := fmt.Sprintf(
		"*This %s was partially generated by AI using [Triage Factory](https://github.com/sky-ai-eng/triage-factory).*",
		kind,
	)
	bare := "\n\n---\n" + disclaimer

	ctx := context.Background()
	run, err := agentRuns.Get(ctx, runmode.LocalDefaultOrg, runID)
	if err != nil || run == nil {
		return bare
	}

	model := prettyModel(run.Model)
	elapsed := elapsedFromRun(run)
	cost, costPrefix := costFromRun(ctx, agentRuns, runID, run)

	return fmt.Sprintf(
		"\n\n---\n%s\n\nTime: %s | Model: %s | Cost: %s$%.3f",
		disclaimer, elapsed, model, costPrefix, cost,
	)
}

// elapsedFromRun returns the human-readable run duration. Prefers the
// stored DurationMs (populated by CompleteAgentRun); falls back to
// CompletedAt-StartedAt; final fallback is "now - StartedAt" for
// still-running standalone-CLI cases. "?" only on a run with no
// StartedAt, which shouldn't happen in practice.
func elapsedFromRun(run *domain.AgentRun) string {
	if run.DurationMs != nil {
		return prettyDurationMs(*run.DurationMs)
	}
	if run.CompletedAt != nil {
		return prettyDurationMs(int(run.CompletedAt.Sub(run.StartedAt).Milliseconds()))
	}
	if !run.StartedAt.IsZero() {
		return prettyDurationMs(int(time.Since(run.StartedAt).Milliseconds()))
	}
	return "?"
}

// costFromRun resolves the cost USD value plus the "~" prefix
// indicator. Prefers run.TotalCostUSD (canonical, populated at
// CompleteAgentRun); falls back to recomputing from RunTokenTotals
// for the still-running CLI mode. The "~" prefix flags the
// approximate-from-tokens estimate so a reader can tell apart the
// settled cost from a live estimate.
func costFromRun(ctx context.Context, agentRuns db.AgentRunStore, runID string, run *domain.AgentRun) (cost float64, prefix string) {
	if run.TotalCostUSD != nil {
		return *run.TotalCostUSD, ""
	}
	totals, err := agentRuns.TokenTotals(ctx, runmode.LocalDefaultOrg, runID)
	if err != nil {
		return 0, ""
	}
	model := totals.Model
	if model == "" {
		model = run.Model
	}
	return ai.CalculateCostUSD(model, totals.InputTokens, totals.OutputTokens, totals.CacheReadTokens, totals.CacheCreationTokens), "~"
}

// prettyModel turns a verbose model id like "claude-sonnet-4-6" into
// a marketing-friendly "Claude Sonnet". Unknown models pass through
// unchanged so a future model id at least reads as itself rather than
// getting silently relabeled.
func prettyModel(model string) string {
	switch {
	case strings.Contains(model, "opus"):
		return "Claude Opus"
	case strings.Contains(model, "sonnet"):
		return "Claude Sonnet"
	case strings.Contains(model, "haiku"):
		return "Claude Haiku"
	default:
		return model
	}
}

// prettyDurationMs formats a millisecond count as e.g. "42s",
// "2m 13s", or "1h 4m". Hours are the cap — anything longer just
// reads as a big number of hours, which matches the kind of run we
// actually produce (delegated runs cap around minutes; an hour is
// already an outlier).
func prettyDurationMs(ms int) string {
	d := time.Duration(ms) * time.Millisecond
	s := int(d.Seconds())
	if s < 60 {
		return fmt.Sprintf("%ds", s)
	}
	m := s / 60
	s = s % 60
	if m < 60 {
		return fmt.Sprintf("%dm %ds", m, s)
	}
	h := m / 60
	m = m % 60
	return fmt.Sprintf("%dh %dm", h, m)
}
